<?php echo $this->partial('/_partials/email/_defaultHeader.phtml',
    array(
            'appName' => $this->appName,
         )
    );
?>
Dear <?php echo $this->data['typist_name']?>
<br /><br />

Please stop working on the below transcript(s) immediately as there has been a change to the booking.
<br />
<?php foreach($this->data as $data):?>
    <table class="data" style="font-family:helvetica, arial, sans-serif;color:#333;font-size:12px;line-height:18px;margin:0 0 15px;">
        <tr class="first">
            <td class="field">
                <label for="name">File name:</label>
            </td>
            <td class="value">
                <span class="view"><?php echo $data['file_name']; ?></span>
            </td>
        </tr>
        <tr>
            <td class="field">
                <label for="name">Duration:</label>
            </td>
            <td class="value">
                <span class="view"><?php echo $this->displayAudioJobLength($data['length_seconds']); ?></span>
            </td>
        </tr>
        <tr>
            <td class="field">
                <label for="name">Service required:</label>
            </td>
            <td class="value">
                <span class="view"><?php echo $data['transcription_type']; ?></span>
            </td>
        </tr>
        <tr>
            <td class="field">
                <label for="name">Turnaround time:</label>
            </td>
            <td class="value">
                <span class="view"><?php echo $data['turnaround_time']; ?></span>
            </td>
        </tr>
    </table>
<?php endforeach;?>

We will be in touch with more information soon.
<br /><br />

<?php echo $this->partial('/_partials/email/_defaultFooter.phtml',
    array(
            'appName' => $this->appName,
            'appUrl' => $this->appUrl,
            'showThanksMessage' => true
        )
    );
?>