<?php echo $this->partial('/_partials/email/_defaultHeader.phtml',
    array(
            'appName' => $this->appName,
            'title'   => 'URGENT! Proofreading booking change/cancellation.'
         )
    );
?>
Dear <?php echo $this->data['proofreader_name']?>
<br /><br />

Please stop proofreading the below transcript immediately as there has been a change to the booking.
<br />
	<table class="data" style="font-family:helvetica, arial, sans-serif;color:#333;font-size:12px;line-height:18px;margin:0 0 15px;">
 		<tr class="first">
        	<td class="field">
            	<label for="name">Job ID:</label>
			</td>
            <td class="value">
            	<span class="view"><?php echo $this->data['audio_job_id']; ?></span>
            </td>
		</tr>
		<tr>
        	<td class="field">
            	<label for="name">Audio file name:</label>
			</td>
            <td class="value">
            	<span class="view"><?php echo $this->data['file_name']; ?></span>
            </td>
		</tr>
		<tr>
        	<td class="field">
            	<label for="name">Deadline:</label>
			</td>
            <td class="value">
            	<span class="view"><?php echo date('g.ia d.m.y', $this->data['due_date_unix']); ?></span>
            </td>
		</tr>
	</table>
We will be in touch with more information soon.
<br /> <br />
<?php echo $this->partial('/_partials/email/_defaultFooter.phtml',
    array(
            'appName' => $this->appName,
            'appUrl' => $this->appUrl,
            'showThanksMessage' => true
        )
    );
?>
