<?php echo $this->partial('/_partials/email/_defaultHeader.phtml',
    array(
            'appName' => $this->appName,
            'title'   => 'Take Note: New support document(s) received'
         )
    );
?>

This is to confirm safe receipt of the below support document(s) into the Take Note portal. The details are listed below. If you have any enquiries please don't hesitate to get in touch with the bookings team on <?php echo $this->bookingEmail; ?> or <?php echo $this->bookingTelephone; ?>.
<br />

<?php foreach($this->data as $data):?>
	<table class="data" style="font-family:helvetica, arial, sans-serif;color:#333;font-size:12px;line-height:18px;margin:0 0 15px;">
 		<tr class="first">
        	<td class="field">
            	<label for="name">File name:</label>
			</td>
            <td class="value">
            	<span class="view"><?php echo $data['file_name']; ?></span>
            </td>
		</tr>
	</table>
<?php endforeach;?>

<?php echo $this->partial('/_partials/email/_defaultFooter.phtml',
    array(
            'appName'           => $this->appName,
            'appUrl'            => $this->appUrl,
            'showThanksMessage' => true
        )
    );
?>