<h1 class="page-title">Users</h1>

<div id="table-utility">
	<div id="utility-links">
		<a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'create'), null, true); ?>" class="no-icon">
			Add new user
		</a>
	</div>
</div>

<div id="container" style="width:100%">
	<table class="index not-fixed-height" id="tbl_users">
	<thead>
		<th>ID</th>
		<th>Name</th>
		<th>Group</th>
		<th>Client</th>
		<th>Email</th>
		<th>Telephone</th>
		<th>&nbsp;</th>
	</thead>
	<tbody>
		<?php echo $this->partialLoop('user/_userRow.phtml', $this->users); ?>
	</tbody>
	<tfoot id="footer-search">
				<tr>
					<th>&nbsp;</th>
					<th><input type="text" name="search_name" value="Search user name" class="search_init" /></th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</tfoot>
	</table>
</div>
<script>
var asInitVals = new Array();
var oTable;
$(document).ready(function() {

	$('.flashmessenger').delay(2000).fadeOut('slow');

    oTable = $('#tbl_users').dataTable({
        "bJQueryUI": true,
        "sPaginationType": "full_numbers",
        "bPaginate": false,
        "bStateSave": true,
        "oLanguage": {
            "sSearch": "Search all columns:",
            "sEmptyTable": "No users available"
        }
    });

    $("tfoot input").keyup( function () {
        /* Filter on the column (the index) of this element */
        // note: add +1 to the index.value as there is no input in col 0 so the index of the text input doesn't match the index of the column being queried
        oTable.fnFilter(this.value, $("tfoot input").index(this)+1);
    } );


    /*
     * Support functions to provide a little bit of 'user friendlyness' to the textboxes in
     * the footer
     */
    $("tfoot input").each( function (i) {
        asInitVals[i] = this.value;
    } );

    $("tfoot input").focus( function () {
        if ( this.className == "search_init" )
        {
            this.className = "";
            this.value = "";
        }
    } );

    $("tfoot input").blur( function (i) {
        if ( this.value == "" )
        {
            this.className = "search_init";
            this.value = asInitVals[$("tfoot input").index(this)];
        }
    } );
} );

function deactivate(id) {

	if (id === "undefined") {
		alert("No user selected");
		return false;
	}

	if (confirm("Confirm deactivation of user ID " + id + "?")) {
		// do nothing - continue
	} else {
		return false;
	}

	var url ="<?php echo $this->url(array('controller' => 'user', 'action' => 'deactivation'), null, true); ?>"
	url += "/id/" + id;

	$.ajax({
		type: "GET",
	  	url: url,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {
		if (msg.status == "ok") {
			alert("User deactivated");
			$("#list-user-actions-cell-" + id).html(msg.msg);
		} else {
			alert("User could not be deactivated");
		}
	});
}

function activate(id) {

	if (id === "undefined") {
		alert("No user selected");
		return false;
	}

	if (confirm("Confirm activation of user ID " + id + "?")) {
		// do nothing - continue
	} else {
		return false;
	}

	var url ="<?php echo $this->url(array('controller' => 'user', 'action' => 'activation'), null, true); ?>"
	url += "/id/" + id;

	$.ajax({
		type: "GET",
	  	url: url,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {
		if (msg.status == "ok") {
			alert("User activated");
			$("#list-user-actions-cell-" + id).html(msg.msg);
		} else {
			alert("User could not be activated");
		}
	});
}


</script>