<tr id="tr-<?php echo $this->id; ?>">
	<td>
		<?php echo $this->escape($this->id); ?>
	</td>
    <td>
		<?php echo $this->escape($this->name); ?>
    </td>
    <td>
    	<?php echo $this->escape($this->description); ?>
	</td>
	<td>
    	<?php echo $this->escape($this->price); ?>
	</td>
    <td>
        <a href="<?php echo $this->url(array('controller' => 'additional-service', 'action' => 'edit', 'id' => $this->id), null, true); ?>" class="to_person">Edit</a> |
        <a href="<?php echo $this->url(array('controller' => 'additional-service', 'action' => 'delete', 'id' => $this->id), null, true); ?>" class="confirmBox">Delete</a>
    </td>
</tr>