<h1>Search</h1>
<p>Search audio job file names.</p>
<form action="" method="GET" id="searchForm">
    <table>
        <tr>
            <td class="field"><label for="q">Search</label></td>
            <td class="value"><input type="text" name="q" id="q" value="<?php echo $this->query; ?>" /></td>
        </tr>
        <tr>
            <td>
                &nbsp;
            </td>
            <td>
                <a href="#" class="button-img" onclick="searchForm.submit();return false;">
                    <img style="vertical-align:text-top;" src="<?php echo $this->baseUrl() . '/images/submit_button.png' ?>" title="Search">
                </a>
            </td>
        </tr>
    </table>
</form>

<?php

if ( count( $this->results ) > 0 )
{
?>
<p><?php echo count( $this->results ) . ' ' . ( ( count( $this->results ) === 1 ) ? 'Result' : 'Results' ); ?></p>
    <?php
    if ( 'audiojob' === $this->type )
    {
    ?>
<table>
    <tr>
        <th><h3>Project Title (PO Number)</h3></th>
        <th><h3>Audio Job File Name</h3></th>
    </tr>
<?php
    foreach ( $this->results as $result )
    {
        ?>
        <tr>
            <td class="field"><p><?php echo $result->getJob()->title . ' (' . $result->getJob()->po_number . ')'; ?></p></td>
            <td class="value"><p><a href="<?php echo $this->url( array( 'controller' => 'job', 'action' => 'view', 'id' => $result->job_id ), null, true ); ?>"><?php echo $result->file_name; ?></a></p></td>
        </tr>
        <?php
    }
?>
</table>
<?php
    }
    else
    {
        ?>
    <table>
    <tr>
        <th><h3>Project ID</h3></th>
        <th><h3>Project Title (PO Number)</h3></th>
        <th><h3>Status</h3></th>
        <th><h3>Completed</h3></th>
        <th><h3>Invoiced</h3></th>
        <th><h3>Archived</h3></th>
        <th><h3>Deleted</h3></th>
        <th><h3>Total</h3></th>
    </tr>
<?php
    foreach ( $this->results as $result )
    {
        ?>
        <tr>
            <td class="value"><p><?php echo $result->id; ?></p></td>
            <td width="200px" class="value"><p><?php echo $result->title . ' (' . $result->po_number . ')'; ?></p></td>
            <td class="value">
                <p>
                    <?php
                    if ( $result->isDeleted() )
                    {
                        echo $result->getStatus()->name;
                    }
                    else
                    {
                    ?>
                    <a href="<?php echo $this->url( array( 'controller' => 'job', 'action' => 'view', 'id' => $result->id ), null, true ); ?>"><?php echo $result->getStatus()->name; ?></a>
                    <?php
                    }
                    ?>
                </p>
            </td>
            <td class="value"><p><?php echo ( $result->isComplete() ) ? 'Y' : 'N' ;?></p></td>
            <td class="value"><p><?php echo ( $result->isInvoiced() ) ? 'Y' : 'N' ;?></p></td>
            <td class="value"><p><?php echo ( $result->isArchived() ) ? 'Y' : 'N' ;?></p></td>
            <td class="value"><p><?php echo ( $result->isDeleted() ) ? 'Y' : 'N' ;?></p></td>
            <td class="value"><p><?php echo ( $result->isDeleted() ) ? '-' : "£" . number_format( $result->getPrice(), 2 );?></p></td>
        </tr>
    <?php
    }
?>
</table>
<?php
    }
}

