<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
    <head>
        <style>
            body{
                padding:0;
                font-family:Arial, sans-serif;  
            }
            table{
                width:750px;
                font-size:12px;
                table-layout:fixed;
            }
            h1{
                color:#95D336;
            }
            #main-table, #info-table{
                margin-top:20px;
                margin-bottom:20px;
                table-layout:fixed;
            }
            #main-table th{
                text-align:center;
                padding:5px 0;
                border:0.5px solid #bfbfb8;
            }
            #main-table td, #info-table td{
                border:0.5px solid #bfbfb8;
                padding:5px;
                overflow-wrap:break-word;
                table-layout:fixed;
                white-space:normal;
            }
            #declare{
                width:750px;
            }
            #bank-details th, #bank-details td{
                border:0.5px solid #bfbfb8;
                padding:5px;
                text-align:center;
            }

            
        </style>
    </head>
    <body>
        
        <table cellpadding="0" cellspacing="0" border="0" width="750">
            <tr>
                <td>
                    <table cellpadding="0" cellspacing="0" border="0">
                        <tr>
                            <td height="53" style="border-bottom:1px solid #bfbfb8;">
                                <img src="images/invoice_heading.png" alt="Take note" style="display:block;" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <h1>Invoice</h1>
                            </td>
                        </tr>
                    </table>
                    <table id="info-table" cellpadding="0" cellspacing="0" border="0" width="750">
                        <tr>
                            <td width="345">Invoice Reference:</td>
                            <td width="355" align="right"><?php echo $this->invoice->name; ?></td>
                        </tr>
                        <tr>
                            <td width="345">Date Generated:</td>
                            <td width="355" align="right"><?php echo date( 'd/m/Y', strtotime( $this->invoice->created_date ) ); ?></td>
                        </tr>

                        <tr>
                            <td width="345">Date Range:</td>
                            <td width="355" align="right"><?php echo date( 'd/m/Y', strtotime( $this->invoice->date_start ) ); ?> - <?php echo date( 'd/m/Y', strtotime( $this->invoice->date_end ) ); ?> </td>
                        </tr>

                        <tr>
                            <td width="345">Name:</td>
                            <td width="355" align="right"><?php echo $this->invoice->getUser()->name; ?></td>
                        </tr>
                        <tr>
                            <td width="345">Address:</td>
                            <td width="355" align="right"><?php echo $this->invoice->getUser()->address; ?></td>
                        </tr>
                        <tr>
                            <td width="345">Work Completed For:</td>
                            <td width="355" align="right">Take Note Ltd, 45 Great Guildford Street, London, SE1 0ES</td>
                        </tr>
                        <tr>
                            <td width="345">Payment Terms:</td>
                            <td width="355" align="right">14 Days</td>
                        </tr>
                    </table>
                    <div id="declare">
                        <p>
                            <strong>
                                I declare that I am registered/have started the process to register as self-employed with HMRC and understand that whilst working with Take Note I am responsible for declaring the Tax and National Insurance on my earnings.
                            </strong>
                        </p>
                    </div>
                    <table id="bank-details" cellpadding="0" cellspacing="0" border="0" width="750" style="margin-top:20px; width:750px;">
                        <tr>
                            <th colspan="4">Bank details for payments via BACS</th>
                        </tr>
                        
                        <tr>
                            <th width="164">Account Name</th>
                            <th width="164">Sort Code</th>
                            <th width="164">Account Number</th>
                            <th width="164">UTR Number</th>
                        </tr>
                        <tr>
                            <td><?php echo ( !empty( $this->invoice->getUser()->acc_name ) ) ? $this->invoice->getUser()->acc_name : '-'; ?></td>
                            <td><?php echo ( !empty( $this->invoice->getUser()->sort_code ) ) ? $this->invoice->getUser()->sort_code : '-'; ?></td>
                            <td><?php echo ( !empty( $this->invoice->getUser()->acc_no ) ) ? $this->invoice->getUser()->acc_no : '-'; ?></td>
                            <td><?php echo ( !empty( $this->invoice->getUser()->utr_no ) ) ? $this->invoice->getUser()->utr_no : '-'; ?></td>
                        </tr>

                    </table>
                </td>
            </tr>
        </table>

        <table id="main-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th width="116">Date</th>
                <th width="28">Project ID</th>
                <th width="108">Project Status</th>
                <th width="100">File Name</th>
                <th width="100">File Type</th>
                <th width="45">Pay Per Min</th>
                <th width="45">Duration</th>
                <th width="28">Total</th>
            </tr>
            <?php
            foreach ($this->invoice->getRecords() as $record)
            {
                ?>
                <tr>
                    <td width="116"><?php echo date( 'd/m/Y', strtotime( $record->getDisplayDate() ) ); ?></td>
                    <td width="28"><?php echo $record->getDisplayId(); ?></td>
                    <td width="108"><?php echo $record->getProjectStatus(); ?></td>
                    <td width="100"><?php echo wordwrap( $record->getRecordName(), 14, '<br />', true ); ?></td>
                    <td width="100"><?php echo wordwrap( $record->getTranscriptionType(), 14, '<br />', true ); ?></td>
                    <td width="45"><?php echo $record->getPricePerMinute(); ?></td>
                    <td width="45"><?php echo $record->getMinutesWorked(); ?></td>
                    <td width="28">&pound;<?php echo number_format($record->getAmountDue(), 2); ?></td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <th colspan="7" align="right">Invoice Total:</th>
                <td>&pound;<?php echo number_format($this->invoice->getTotalAmountDue(), 2); ?></td>
            </tr>
        </table>

    </body>
</html>