
<div id="login-box">
    <?php echo $this->flashMessenger(); ?>
	<h1>
		<img src="/images/logo2.png" alt="Take Note" />
	</h1>
	<h2>
		Import Users
	</h2>
    <form action="<?php echo $this->url(array('module' => 'default', 'controller' => 'import-user', 'action' => 'process'), null, true); ?>" method="post" enctype="multipart/form-data">
        <label for="file">CSV File:</label>
        <input type="file" name="file" id="file" />
        <label>User Type: </label>
        <label>Staff: </label><input type="radio" name="user_type" value="staff" <?php if (isset($this->userType) && 'staff' == $this->userType):?>checked="checked"<?php endif; ?>/>
        <label>Client: </label><input type="radio" name="user_type" value="client" <?php if (isset($this->userType) && 'client' == $this->userType):?>checked="checked"<?php endif; ?>/>
        <br />
        <input type="submit" name="submit" value="Upload" />
    </form>
</div>