<!doctype html>
<html lang="en">
<head>
<title></title>
<meta charset="utf-8" />
<link rel="stylesheet" type="text/css" href="css/styles.css" />
</head>
<body style="padding:0;margin:0;">

<style type="text/css">

</style>

<table cellpadding="0" cellspacing="0" border="0" width="100%" height="100%">
	<tr>
		<td valign="top" align="center">

			<table cellpadding="0" cellspacing="0" border="0" width="600">
				<tr>
					<td height="53" style="border-bottom:1px solid #bfbfb8;">
						<?php if (isset($this->headerImagePath) && !empty($this->headerImagePath)): ?>
                            <img src="<?php echo $this->headerImagePath; ?>" alt="Take note" style="display:block;" />
                        <?php else: ?>
                            <img src="<?php echo $this->serverUrl() . $this->baseUrl('/images/email-header.gif'); ?>" alt="Take note" style="display:block;" />
                        <?php endif; ?>
					</td>
				</tr>
				<tr>
					<td id="email-content">
                         <h1 style="font-family:helvetica, arial, sans-serif;color:#525252;font-size:16px;background:#95d336;margin:0 0 15px;padding:15px;"><?php if (isset($this->title)) echo $this->title; ?></h1>
                         <?php if (isset($this->subTitle)): ?><h2 style="font-family:helvetica, arial, sans-serif;color:#525252;font-size:16px;margin:0 0 15px;"><?php echo $this->subTitle; ?></h2><?php endif; ?>
                            <p style="font-family:helvetica, arial, sans-serif;color:#333;font-size:12px;line-height:18px;margin:0 0 15px;">