<?php
if ( $this->service instanceof Application_Model_Service_Row && count( $this->service->getServicePriceModifiers() ) > 0 )
{
    ?>
<table>
    <tbody>
    <?php
    foreach ( $this->service->getServicePriceModifiers() as $priceModifier )
    {
        $checked = '';
        if ( ( $this->audioJob && $this->audioJob->hasPriceModifier( $priceModifier->id ) ) || ( is_array( $this->modifiers ) && in_array( $priceModifier->id, $this->modifiers ) ) )
        {
            $checked = ' checked="checked"';
        }
        ?>
        <tr style="border-bottom: 1px dotted gray;">
            <td width="150px">
                <?php echo $priceModifier->getPriceModifier()->name; ?>
            </td>
            <td>
                <input class="checkbox-modifier"<?php echo $checked;?> type="checkbox" name="price_modifiers[]" value="<?php echo $priceModifier->id; ?>" />
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
    <?php
}