<div class="select-job-user-container">
    <div class="ui-state-default ui-widget-content ui-widget-header">
        <h3>Service Information</h3>
    </div>
<table class="data">
    <?php
    foreach ( $this->services as $service )
    {
        ?>
        <tr>
            <td class="field"><strong><?php echo $service->name; ?></strong></td>
            <td class="value"><?php echo $service->description; ?></td>
        </tr>
    <?php
    }
    ?>
</table>
<div class="ui-state-default ui-widget-content ui-widget-header">
    <h3>Additional Service Information</h3>
</div>
<table class="data">
    <?php
    foreach ( $this->additionalServices as $additionalService )
    {
        ?>
        <tr>
            <td class="field"><strong><?php echo $additionalService->name; ?></strong></td>
            <td class="value"><?php echo $additionalService->description; ?></td>
        </tr>
    <?php
    }
    ?>
</table>
</div>