<tr>
    <td class="field"><span class="view"><?php echo $this->areaName; ?>(<?php echo $this->formatScore($this->maxAreaScore); ?>)</span></td>
    <td>
        <div class="element-error error-inner">
            <?php echo $this->formatScore($this->score); ?>
        </div>
    </td>
    <td>
        <span class="view">
            <?php echo $this->comment; ?>
        </span>
    </td>
    <td>
        <span class="view"><?php echo $this->criteria; ?></span>
    </td>
</tr>