<?php echo $this->partial('/_partials/email/_defaultHeader.phtml',
    array(
            'appName'  => $this->appName,
            'title'    => 'Access Password',
            'subTitle' => 'Your new password is below'
        )
    );
?>

        <strong>Username:</strong> <?php echo $this->escape($this->username); ?><br />
        <strong>Password:</strong> <?php echo $this->escape($this->password); ?><br /><br />

        Please enter a memorable sentence in the passphrase field to be used with your login details in the future. <br /><br />

        Please keep your password safe to prevent unauthorised access. You can login at <a href="<?php echo $this->appUrl; ?>" style="font-family:helvetica, arial, sans-serif;color:#333;font-size:12px;"><?php echo $this->appName; ?></a>

<?php echo $this->partial('/_partials/email/_defaultFooter.phtml',
    array(
            'appName' => $this->appName,
            'appUrl' => $this->appUrl
        )
    );
?>