<?php echo $this->escape($this->appName); ?> Access Password
------------------------------------------------------------------

<?php echo $this->escape($this->translate('Your new password is below.')); ?>

<?php echo $this->escape($this->translate('Username')); ?>: <?php echo $this->escape($this->username); ?>
<?php echo $this->escape($this->translate('Password')); ?>: <?php echo $this->escape($this->password); ?>

<?php echo $this->escape($this->translate('Please enter a memorable sentence in the passphrase field to be used with your login details in the future.')); ?>

<?php echo $this->escape($this->translate('Please keep your password safe to prevent unauthorised access.')); ?>

<?php echo $this->escape($this->translate('You can login at')); ?>:
<?php echo $this->appUrl; ?>
