<?php echo $this->partial('/_partials/email/_defaultHeader.phtml',
    array(
          'appName' => $this->appName,
          'title' => ' Password reset request'
         )
   );
?>
        <p><?php echo $this->escape($this->translate('Hello.')); ?></p>
        We have received a request to reset the password for the following username.
        To reset your password please click on <a href="<?php echo $this->passwordResetUrl; ?>">this</a> link, if you did not request a change please ignore this email.<br /><br />

        <strong><?php echo $this->escape($this->translate('Username')); ?>:</strong> <?php echo $this->escape($this->username); ?><br />

        <p>
        <?php echo $this->escape($this->translate('Thankyou'));?><br />
        <?php echo $this->escape($this->translate('The Take Note Team'));?>


<?php echo $this->partial('/_partials/email/_defaultFooter.phtml',
    array(
            'appName' => $this->appName,
            'appUrl' => $this->appUrl
        )
    );
?>