<?php echo $this->escape($this->appName); ?> Password Reset Request
------------------------------------------------------------------

<p><?php echo $this->escape($this->translate('Hello.')); ?></p>

<?php echo $this->escape($this->translate('We have received a request to reset the password for the following username. To reset your password please click on this link, if you did not request a change please ignore this email.')); ?><br /><br />

<?php echo $this->appUrl; ?>

<?php echo $this->passwordResetUrl; ?>

<p><?php echo $this->escape($this->translate('Thankyou'));?></p><br>

<p><?php echo $this->escape($this->translate('The Take Note Team'));?>

<p><a href="<?php echo $this->appUrl; ?>"><?php echo $this->appUrl; ?></a></p>