<div class="ui-state-default ui-widget-content ui-widget-header">
	<h3 style="padding:5px">Adding Ad-hoc charges to Job ID: <?php echo $this->job['id']?>
		<span style="color: #A8A8A8; font-size: 75%">
		<?php if (strlen($this->job['title']) > 50) {
			echo substr($this->job['title'], 0, 50) . '...';
		} else {
			echo $this->job['title'];
		}?>
		</span>
	</h3>
</div>

<?php
$this->form->setAction($this->url());
?>

<div>
    <p class="validateTips">Form fields marked with * are required.</p>
    <form id="formAdHocCharge" method="<?php echo $this->form->getMethod(); ?>" action="<?php echo $this->form->getAction(); ?>">
        <?php echo $this->form->job_id; ?>
        <table class="data">
            <tr>
                <td class="field">
                    <label for="price">Price*:</label>
                </td>
                <td class="value">
                    <span class="view"><?php echo $this->form->price; ?></span>
                </td>
            </tr>
            <tr>
                <td class="field">
                    <label for="description">Description:</label>
                </td>
                <td class="value">
                    <span class="view"><?php echo $this->form->description; ?></span>
                </td>
            </tr>
		    <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    <?php //echo $this->form->submit; ?>
                    <a href="#" onclick="processAdHocCharges();return false;">
                    	<img src="<?php echo $this->baseUrl() .'/images/submit_button.png'?>" title="Save job" class="button-img">
                    </a>
                    <a href="#" onclick="$('#job-dialog-adhoc').dialog('close'); return false;" class="button-img">
				    	<img src="<?php echo $this->baseUrl() .'/images/cancel_button.png'?>" title="Cancel job">
				    </a>
                </td>
            </tr>
        </table>
    </form>
    <div class="ui-state-default ui-widget-content ui-widget-header">
        <h3 style="padding:5px">Current Ad-hoc charges for Job ID: <?php echo $this->job['id']?>
            <span style="color: #A8A8A8; font-size: 75%">
            <?php if (strlen($this->job['title']) > 50) {
                echo substr($this->job['title'], 0, 50) . '...';
            } else {
                echo $this->job['title'];
            }?>
            </span>
        </h3>
    </div>
    <?php
    if (count($this->current) > 0)
    {
    ?>
    <table class="data">
        <?php
        foreach ($this->current as $adhoc)
        {
            ?>
            <tr id="adhoc<?php echo $adhoc['id'];?>">
                <td>
                    <?php echo $adhoc['description']; ?>
                </td>
                <td>
                    &pound;<?php echo number_format($adhoc['price'], 2); ?>
                </td>
                <td>
                    <a href="#" onclick="deleteAdhoc('<?php echo $adhoc['id'] ;?>')">
                        <img src="/images/icons/delete.png" alt="Delete Ad-hoc" />
                    </a>
                </td>
            </tr>
            <?php
        }
        ?>
    </table>
    <?php
    }
    ?>
</div>

<script>
	$(function() {
		$( "#btn_save" ).button();
		$( "#btn_cancel" ).button();
	});
</script>