<!--
/*
 * jQuery File Upload Plugin Demo 6.9
 * https://github.com/blueimp/jQuery-File-Upload
 *
 * Copyright 2010, Sebastian Tschan
 * https://blueimp.net
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/MIT
 */
-->
    <!-- Bootstrap CSS Toolkit styles -->
    <!-- <link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/blueImpUpload/bootstrap.min.css">
    <!-- Generic page styles -->
    <!-- link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/css/style.css">-->
    <!-- Bootstrap styles for responsive website layout, supporting different screen sizes -->
    <!-- <link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-responsive.min.css">-->
    <!-- Bootstrap CSS fixes for IE6 -->
    <!--[if lt IE 7]><link rel="stylesheet" href="http://blueimp.github.com/cdn/css/bootstrap-ie6.min.css"><![endif]-->
    <!-- Bootstrap Image Gallery styles -->
    <!--<link rel="stylesheet" href="http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css">-->
    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/css/jquery.fileupload-ui.css">
    <!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

<script>

function showMultiAudio(id)
{
    if ($('#show-multi-audio-' + id).is(':checked'))
    {
        $('#multi-audio-row-' + id).show();
    }
    else
    {
        $('#multi-audio-row-' + id).hide();
        $('lead_id-' + id).val(0);
    }

}

</script>
<div id="file-upload">
<h1>Upload</h1>
<h2>Adding files to project ID <?php echo $this->job['id']; ?></h2>
<div>
	<table class="data">
 		<tr class="first">
        	<td class="field">
            	<label for="title">Title:</label>
            </td>
            <td class="value">
            	<span class="view"><?php echo $this->job['title']; ?></span>
            </td>
        </tr>
        <tr>
        	<td class="field">
            	<label for="email">Due Date:<span class="required">*</span></label>
			</td>
            <td class="value">
            	<span class="view"><?php echo date('d/m/Y', strtotime($this->job['job_due_date'])); ?></span>
			</td>
		</tr>
	</table>
</div>

<div class="container">

<div class="upload-warning">Please do not log out of system until all file uploads are complete.</div>
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" action="<?php echo $this->url(array('controller' => 'job', 'action' => 'upload'), null, true); ?>" method="POST" enctype="multipart/form-data">

        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="span10">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white"></i>
                    <span>Add audio files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <!--
                <span class="btn btn-success fileinput-button">
                    <i class="icon-plus icon-white" ></i>
                    <span>Add support documents...</span>
                    <input type="file" name="support_files[]" multiple>
                </span>
                -->
                <button type="submit" class="btn btn-primary start">
                    <i class="icon-upload icon-white"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-danger cancel">
                    <i class="icon-ban-circle icon-white"></i>
                    <span>Cancel upload</span>
                </button>
               <button type="button" class="btn btn-danger delete" onclick="if (confirmCancel()) window.close();window.opener.document.location.reload(false);">
                    <span>Close window</span>
                </button>
            </div>
            <!-- The global progress information -->
            <div class="span5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="bar" style="width:0%;"></div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The loading indicator is shown during file processing -->
        <div class="fileupload-loading"></div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
    </form>
</div>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">

        <td class="name" style="width:150px"><span>{%=file.name%}</span>
		<br />

		<input type="hidden" name="doc_type" value="{%=file.docType%}" />

		</td style="width:100px">
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span>
        {% if (file.docType == 'audio') { %}
<p style="margin-top:18px">
<label class="service_id_view">Service:<br />
							<select class="transcription_type" name="service[]" required style="width:150px" onchange="$(this).css('background-color', 'inherit')">
								<option value="">-- select --</option>
<?php foreach($this->services as $key => $option): ?>
            <option value="<?php echo $key?>" <?php if($this->job['service_id'] == $key):?>selected<?php endif;?>><?php echo $option?></option>
<?php endforeach;?>
							</select>
						</label>
</p>
    <?php
    if (count($this->audioJobs) > 0)
    {
    ?>

<p>
    <label>Multipart audio:<br />
        For multipart audio files, check to assign this file to another audio file.<br />
        <input type="checkbox" id="show-multi-audio-{%=String(i)%}" onclick="javascript:showMultiAudio({%=String(i)%})">
    </label>
</p>
<p id="multi-audio-row-{%=String(i)%}" style="margin-top:18px; display:none;">
    <label>Select Lead Job:<br />
        <select name="lead_id[]" id="lead_id-{%=i%}" style="width:150px" onchange="$(this).css('background-color', 'inherit')">
            <option value="">-- select --</option>
        <?php foreach($this->audioJobs as $option): ?>
            <option value="<?php echo $option['id']?>"><?php echo $option['file_name']?></option>
        <?php endforeach;?>
        </select>
    </label>
</p>
<?php
    }
?>
<p style="margin-top:10px">
<label>Audio Quality:<br />
							<select name="audio_quality[]" required onchange="$(this).css('background-color', 'inherit'); <?php echo $this->audioFileQualitiesWarningJs ?>" style="width:150px">
								<option value="">-- select --</option>
							<?php foreach($this->audioFileQualities as $option): ?>
								<option value="<?php echo $option['key']?>" <?php if($this->job['audio_quality_id'] == $option['key']):?>selected<?php endif;?>><?php echo $option['value']?></option>
							<?php endforeach;?>
						</select>
</p>
{% } %}
</td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td style="width:100px">
                <div style="width:150px" class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>

{% if (file.docType == 'audio') { %}
<p>
    <label class="speaker_numbers_view">
        <?php
    echo $this->partial( 'job/_partials/upload/_speakerNumbers.phtml', 'default', array( 'job' => $this->job, 'speakerNumbers' => $this->speakerNumbers ) );
    ?>
    </label>
</p>
<p style="margin-top:10px">
    <label class="turnaround_time_view">
        <?php
    echo $this->partial( 'job/_partials/upload/_turnaroundTimes.phtml', 'default', array( 'job' => $this->job, 'turnaroundTimes' => $this->turnaroundTimes ) );
    ?>
    </label>
</p>
<p>
   <label>Additional Services:</label>
        <span class="view modifiers_view">
        <?php echo $this->partial( 'job/_partials/upload/_priceModifiers.phtml', 'default',  array( 'service' => $this->service, 'modifiers' => unserialize( $this->job->modifiers ) ) ); ?>
    </span>
</p>
{% } %}
            </td style="width:150px">
            <td class="start"><span style="display:none">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}M</span>
<p style="margin-top:8px">
<label>Comments:<br />
							<textarea name="client_comments[]" value="" style="width:350px" rows="4"/>
						</label>

</p>
</td>
        {% } else { %}
            <td colspan="1"></td>
        {% } %}
			<td class="cancel">{% if (!i) { %}
            <button class="btn btn-danger">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>

</tr>


{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else if (file.no_file_length && file.no_file_length == true) { %}
        	<td colspan="4" class="name">
        		<span id="container-reupload-img-{%=file.file_id%}">
            		<img src="<?php echo $this->baseUrl(); ?>/images/icons/cross.png">
            	</span>
            	&nbsp;{%=file.name%}
            </td>
			<td class="size" colspan="3">
				<div id="container-reupload-form-{%=file.file_id%}">
					<form id="{%=file.file_id%}" name="{%=file.file_id%}" action="<?php echo $this->url(array('controller' => 'job', 'action' => 'upload'), null, true); ?>" method="POST">
					<input type="hidden" id="id" name="id" value="{%=file.file_id%}" />
					<input type="hidden" id="audio_upload_key" name="audio_upload_key" value="{%=file.upload_key%}" />
					<input type="hidden" id="upload_file_count" name="upload_file_count" value="{%=file.upload_file_count%}" />
					<span>Unfortunately, although we've safely received your sound file, we couldn't<br />automatically determine the duration of this file.</span>
					<p>Please enter the duration of this file in hours and minutes and then click the 'Submit' button to the left.</p>
					<p>If the file isn't a sound file and needs to be deleted, please click the 'Delete' button instead.</p>
					<div style="width:150px">
						<span style="width:65px; float:left; font-size:90%">Hours</span>
							<span style="width:75px; float:right;font-size:90%">
							<select name="hours" id="hours" style="width:75px;" required>
								<option value="">select</option>
								<option value="0">0</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
								<option value="6">6</option>
								<option value="7">7</option>
								<option value="8">8</option>
								<option value="9">9</option>
								<option value="10">10</option>
							</select>
						</span>
					</div>
					<div style="clear:both"></div>
					<div style="width:150px">
						<span style="width:65px; float:left; font-size:90%">Minutes</span>
						<span style="width:75px; float:right;font-size:90%">
							<select name="minutes" id="minutes" style="width:75px" required>
								<option value="">select</option>
								<option value="00">00</option>
								<option value="05">05</option>
								<option value="10">10</option>
								<option value="15">15</option>
								<option value="20">20</option>
								<option value="25">25</option>
								<option value="30">30</option>
								<option value="35">35</option>
								<option value="40">40</option>
								<option value="45">45</option>
								<option value="50">50</option>
								<option value="55">55</option>
							</select>
						</span>
					</div>
					</form>
				</div>
                	<div id="container-reupload-btn-{%=file.file_id%}">
                        <button class="btn btn-primary" id="btn-submit-time-{%=file.file_id%}" onclick="return prepareReloadData({%=file.file_id%});">
                            <i class="icon-upload icon-white"></i>
                            <span>Submit</span>
                        </button>
                        <button class="btn btn-danger" id="btn-submit-time-{%=file.file_id%}" onclick="deleteFile({%=file.file_id%});">
                            <i class="icon-ban-circle icon-white"></i>
                            <span>Delete</span>
                        </button>
           </div>
		</td>
		<td class="start">

        </td>
        {% } else { %}
            <td colspan="4" class="name">
				<audio autoplay src="<?php echo $this->baseUrl(); ?>/sound/ding.wav" type="audio/wav">
					<embed src="<?php echo $this->baseUrl(); ?>/sound/ding.wav" autostart="true" width="0" height="0" id="sound1"
					enablejavascript="true">
				</audio>
                <img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png">&nbsp;{%=file.name%}
            </td>
            <td class="size"><span>Upload Complete:&nbsp;:{%=file.size%}</span></td>
            <td colspan="2"></td>
        {% } %}
    </tr>
{% } %}
</script>
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>-->
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<!--<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/vendor/jquery.ui.widget.js"></script>-->
<!-- The Templates plugin is included to render the upload/download listings -->
<!-- <script src="http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"></script> -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpJavascriptTemplates/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<!--<script src="http://blueimp.github.com/JavaScript-Load-Image/load-image.min.js"></script>-->
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<!--<script src="http://blueimp.github.com/JavaScript-Canvas-to-Blob/canvas-to-blob.min.js"></script>-->
<!-- Bootstrap JS and Bootstrap Image Gallery are not required, but included for the demo -->
<!--<script src="http://blueimp.github.com/cdn/js/bootstrap.min.js"></script>-->
<!--<script src="http://blueimp.github.com/Bootstrap-Image-Gallery/js/bootstrap-image-gallery.min.js"></script>-->
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/jquery.fileupload.js"></script>
<!-- The File Upload file processing plugin -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/jquery.fileupload-fp.js"></script>
<!-- The File Upload user interface plugin -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/jquery.fileupload-ui.js"></script>
<!-- The localization script -->
<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/locale.js"></script>
<!-- The main application script -->
<!--<script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/js/main.js"></script> -->
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!-- [if gte IE 8]><script src="<?php echo $this->baseUrl(); ?>/js/blueImpUpload/<script src="js/cors/jquery.xdr-transport.js"></script><![endif]-->
<script>
var support_file_count = 0;
var audio_file_count = 0;
var support_send_count = 0;
var audio_send_count = 0;

var audio_upload_key_part = Math.round(+new Date()/1000);
var support_upload_key_part = Math.round(+new Date()/1000);



//  window.onbeforeunload = confirmExit;

//  function confirmExit()
//  {
//    return "Are you sure you wish to leave this page?";
//  }

$(function () {
	'use strict';

	$(window).bind('beforeunload', function(){
		return "Sure you want to leave this page?"
	});

	$(window).bind('unload', function(){

		var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'cleanup-on-upload-close'), null, true); ?>";
		url += "/job_id/<?php echo $this->job['id']?>";

		$.ajax({
			type: "POST",
		  	url: url,
		  	//data: formData,
		  	cache: false,
		  	dataType: "json"
		}).success(function( msg ) {

		});
	});

	// Initialize the jQuery File Upload widget:
	$('#fileupload').fileupload({
			progressInterval: 100,
			bitrateInterval: 2500
	});

	$('#fileupload').bind('fileuploadsubmit', function (e, data) {

	    var inputs = data.context.find(':input');
	    if (inputs.filter('[required][value=""]').length) {
	    	inputs.filter('[required][value=""]').css('background-color', '#FFFFB3');
    		alert('Please complete the highlighted fields');
	        return false;
	    }

		//return false;
		data.formData = null;
	    data.formData = inputs.serializeArray();
		data.formData.push({'name':'job_id', 'value':'<?php echo $this->job['id']?>'});


		if (data.files[0].docType == 'audio') {
			data.formData.push({'name':'client_due_date', 'value':'<?php echo $this->job['job_due_date']?>'});
			data.formData.push({'name':'audio_upload_key', 'value':'<?php echo $this->job['id']?>-<?php echo $this->userId ?>-' + audio_upload_key_part});
			data.formData.push({'name':'audio_upload_file_count', 'value':audio_file_count});

			if (audio_send_count > 0) {
				audio_send_count = audio_send_count -1;
			}

			if (audio_send_count == 0) {
				audio_file_count = 0;
				audio_upload_key_part = Math.round(+new Date()/1000);
			}
		} else if(data.files[0].docType == 'support') {
			data.formData.push({'name':'support_upload_key', 'value':'<?php echo $this->job['id']?>-<?php echo $this->userId ?>-' + support_upload_key_part});
			data.formData.push({'name':'support_upload_file_count', 'value':support_file_count});

			if (support_send_count > 0) {
				support_send_count = support_send_count -1;
			}

			if (support_send_count == 0) {
				support_file_count = 0;
				support_upload_key_part = Math.round(+new Date()/1000);
			}

		}
	});

	$('#fileupload').bind('fileuploadadd', function (e, data)
    {
		if (data.paramName == 'files[]') {
			data.files[0].docType = 'audio';
			audio_file_count++;
			audio_send_count++;
		} else if (data.paramName == 'support_files[]') {
			data.files[0].docType = 'support';
			support_file_count++;
			support_send_count++;
		}
	});

});

function prepareReloadData(id)
{

	var url ="<?php echo $this->url(array('controller' => 'job', 'action' => 'reupload'), null, true); ?>";

	formData = $('#' + id).serializeArray();
	// validation
	if (formData[3].value == '' || formData[4].value == '') {
		alert('Please select numeric values for both hours and minutes');
		return false;
	} else if (formData[3].value == '0' && formData[4].value == '00') {
		alert('Please enter a value greater than zero for the file duration');
		return false;
	}

	$.ajax({
		type: "POST",
	  	url: url,
	  	data: formData,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {

		if (msg.status == "ok") {
			$('#container-reupload-form-'+ id).html(msg.name);
			$('#container-reupload-btn-'+ id).html('');
			$('#container-reupload-img-'+ id).html('<img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png">');
		} else {
		}
	});

    return false;
}

function deleteFile(id)
{
	if (!confirm('Are you sure you wish to proceed to delete this file?')) {
		return false;
	}

	var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'delete-upload'), null, true); ?>";

	formData = new Array();
	formData.push({'name':'id', 'value':id});

	$.ajax({
		type: "POST",
	  	url: url,
	  	data: formData,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {

		if (msg.status == "ok") {
			$('#container-reupload-form-'+ id).html('We have deleted this file from our system.');
			$('#container-reupload-btn-'+ id).html('');
		} else {
			//console.log('Not OK');

		}
	});
}

function cleanup() {
	var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'cleanup-on-upload-close'), null, true); ?>";
		url += "/job_id/<?php echo $this->job['id']?>";

		$.ajax({
			type: "POST",
		  	url: url,
		  	//data: formData,
		  	cache: false,
		  	dataType: "json"
		}).success(function( msg ) {

		});
}
/**
* Creates a pop-up window asking a user to confirm when trying to leave a page.
*
* @compatability Windows IE4+
*/
function closeIt() {
   msg = "Close window?";
   // simply return the msg rather than setting 'event.returnValue' to
   // make it work in non-IE browsers
   // event.returnValue = msg;
   return msg;
}

/**
* Set whether the onbeforeunload event handler should be used.
*
* @param bool on whether the onbeforeunload is used or not.
* @compatability Windows IE4+
*/
function setCloseIt(on) {
   window.onbeforeunload = (on) ? closeIt : null;
}

/**
* Confirms with the user whether to continue with the cancel action.
*/
function confirmCancel() {
   if (confirm('Are you sure you wish to close this window?')) {
       setCloseIt(false);
       return true;
   }
   return false;
}

</script>
<script>

    $( 'body' ).on( 'change', '.service_id_view select', function()
    {
        var parentDiv        = $( this ).closest( 'tr' );
        var turnaround       = $( '.turnaround_time_view', parentDiv );
        var speakerNumbers   = $( '.speaker_numbers_view', parentDiv );
        var modifiers        = $( '.modifiers_view', parentDiv );


        var url ="<?php echo $this->url( array( 'controller' => 'job', 'action' => 'fetch-service-details-upload', 'job_id' => $this->job->id ), null, true ); ?>";
        url += '/service_id/' + $( this ).val() + "/job_id/<?php echo $this->job['id']?>";

        $.ajax({
            type     : 'GET',
            url      : url,
            cache    : false,
            dataType : "json"
        }).success(function( msg )
        {
            speakerNumbers.html( msg.speaker_numbers );
            turnaround.html( msg.turnaround_times );
            modifiers.html( msg.modifiers );
        });
    });
</script>

</div>