<?php echo $this->escape($this->appName); ?> Welcome to the Take Note Portal
------------------------------------------------------------------

<?php echo $this->escape($this->translate('Hi and Welcome to the Take Note Portal! A new account has been created for you and your login details are shown below. ')); ?><br /><br />

<?php echo $this->escape($this->translate('Username')); ?>: <?php echo $this->escape($this->username); ?>
<?php echo $this->escape($this->translate('Password')); ?>: <?php echo $this->escape($this->password); ?>

<?php echo $this->escape($this->translate("Please note: If you are uploading sensitive material, we can set you up with an extra layer of security when logging on to our system, via a 3 word passphrase. If this is of interest of if you have any other issues please don't hesitate to get in touch using either bookings@takenotetyping.com or 0207 928 1048.")); ?>


<?php echo $this->escape($this->translate('Thanks')); ?>
<?php echo $this->escape($this->translate('The Take Note Team')); ?>



