<h1><?php echo $this->group->name; ?></h1>
<form id="editGroup" method="POST" action="/en/default/services/edit-group/id/<?php echo $this->group->id; ?>">
    <input type="hidden" name="service_id" value="<?php echo $this->group->id; ?>" />
    <table>
        <tr>
            <td><label for="name">Name</label></td>
            <td><input type="text" name="name" value="<?php echo $this->group->name; ?>" /></td>
        </tr>
    </table>
<h2>Services</h2>
<table>
    <?php
    foreach ( $this->services as $service )
    {
    ?>
    <tr>
        <td><?php echo $service->name; ?></td>
        <?php
        $checked = '';
        if ( $this->group->hasService( $service->id ) )
        {
            $checked = ' checked="checked"';
        }
        ?>
        <td><input type="checkbox" name="service[]" value="<?php echo $service->id; ?>"<?php echo $checked; ?> /></td>
    </tr>
    <?php
    }
    ?>
</table>
    <div class="ta-block wide">
        <a href="#" id="btn_save" onclick="editGroup.submit();return false;">
            Submit
            <img style="vertical-align:text-top;" src="<?php echo $this->baseUrl() .'/images/icons/accept.png'?>" title="Save">
        </a>
    </div>
</form>