<script>
    $('document').ready(function()
    {
        $('#tbl_services').on('click', '.delete-services', function()
        {
            var confirmDelete = confirm("Are you sure you want to delete this Service?");
            if (confirmDelete == true)
            {
                var link = $(this);
                var components = link.attr('id').split('-');
                var id = components[1];
                $('#delete-form-' + id).submit();
            }
            return false;
        });
    });
</script>

<h1>Services</h1>

<div id="table-utility">
    <div id="utility-links">
        <a href="<?php echo $this->url(array('controller' => 'services', 'action' => 'edit-service'), null, true); ?>" class="no-icon">
            Add new service
        </a>
        <a href="<?php echo $this->url(array('controller' => 'services', 'action' => 'edit-descriptions'), null, true); ?>" class="no-icon">
            Edit descriptions
        </a>
    </div>
</div>
<div id="container" style="width:100%">
    <table class="dataTable index not-fixed-height" id="tbl_services">
        <thead>
            <tr>
                <th><div>Service</div></th>
                <th><div>Edit</div></th>
                <th><div>Delete</div></th>
            </tr>
        </thead>
        <tbody>
        <?php if( count( $this->services ) > 0 ): ?>
            <?php foreach( $this->services as $service ): ?>
                <tr>
                    <td><div><?php echo $service->name; ?></div></td>
                    <td>
                        <div>
                            <a href="<?php echo $this->url( array( 'controller' => 'services', 'action' => 'edit-service', 'id' => $service->id ) ); ?>">
                                Edit
                            </a>
                        </div>
                    </td>
                    <td>
                        <?php
                        if ( $service->canDelete() )
                        {
                            ?>
                            <div>
                                <form method="POST" action="<?php echo $this->url( array( 'controller' => 'services', 'action' => 'delete-service' ), null, true ); ?>" id="delete-form-<?php echo $service->id; ?>">
                                    <input type="hidden" name="service_id" value="<?php echo $service->id; ?>" />
                                </form>
                                <a href="#" id="delete-<?php echo $service->id; ?>" class="confirm-delete delete-services">
                                    <img src="<?php echo $this->baseUrl() .'/images/icons/delete.png'?>" title="Delete Service">
                                </a>
                            </div>
                        <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        </tbody>
        <tfoot>
        <tr id="footer-search">
            <th>&nbsp;</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
        </tfoot>
    </table>
</div>