<div class="ui-state-default ui-widget-content ui-widget-header">
	<h3>
		Select Proofreaders
	</h3>
</div>

<div>
    <form id="formAssignMultipleProofreader">
    	<?php if($this->mode == 'create'):?>
    	<input type="hidden" id="assign-multiple-proofreader-audio_job_id" name="audio_job_id" value="<?php echo $this->escape($this->audioJobId) ?>" />
    	<div id="assign-multiple-proofreaders-select-split">
	    	<label for="number_proofreaders">Enter number of proofreaders required:</label>
			<select name="number_proofreaders" id="number_proofreaders">
				<option>2</option>
				<option>3</option>
				<option>4</option>
				<option>5</option>
				<option>6</option>
			</select>

	    	<a href="#" onclick="splitAudioJobProofreader(<?php echo $this->escape($this->audioJobId); ?>, $('#number_proofreaders').val(), 'create');return false;">
	    		Split job
	   		</a>
	   	</div>
	   	<?php else: ?>
	   	<a href="#" id="assign-multiple-proofreader-add-row" onclick="showAssignMultipleProofreader(<?php echo $this->escape($this->audioJobId); ?>, 'addRow', parseInt($('#assign-multiple-proofreader-add-row-count').val())+1);return false;">
	   		Add new row
	   	</a>
        <?php if ($this->displayUnsplitLink($this->audioJobId, Application_Model_User::PROOFREADER_USER)): ?>
        &nbsp;
        <a href="#" id="assign-multiple-proofreader-unsplit-file" onclick="unsplitMultipleProofreader(<?php echo $this->escape($this->audioJobId); ?>);return false;">
                Unsplit file
            </a>
        <?php endif; ?>
	   	<?php endif;?>
	   	<input type="hidden" id="assign-multiple-proofreader-add-row-count" name="assign-multiple-proofreader-add-row-count" value="<?php echo count($this->data) ?>" />
   		<div id="assign-multiple-proofreader-list-proofreaders">
   			<?php if($this->mode == 'edit' || $this->mode == 'addRow'):?>
	   			<?php echo $this->partial('audio-job/assign-multiple-proofreader-cell.phtml', array(
					'data' 			=> $this->data,
					'audioJobId' 	=> $this->audioJobId,
					'mode'			=> $this->mode,
	   			));
				?>
   			<?php endif;?>
   		</div>
        <table class="data">
            <tr>
                <td>
                    &nbsp;
                </td>
                <td style="text-align:center">
                    <?php //echo $this->form->submit; ?>
                    <a href="#" onclick="submitAssignMultipleProofreader();return false;" <?php if($this->mode == 'create'):?>style="display:none"<?php endif;?> class="button-img">
                    	<img src="<?php echo $this->baseUrl() .'/images/submit_button.png'?>" title="Save job">
                    </a>
                    <a href="#" onclick="$('#job-list-audio-dialog-assign-multiple-proofreader').dialog('close'); return false;" class="button-img">
                    	<img src="<?php echo $this->baseUrl() .'/images/cancel_button.png'?>" title="Cancel job">
                    </a>
                </td>
            </tr>
        </table>
    </form>
</div>