<iframe id="ifr_download" src="" style="display: none;"></iframe>

<div id="job-list-transcription-dialog" style="display: none">
	<span id="job-list-transcription-dialog-container" class="view"></span>
</div>

<div id="job-list-audio-dialog" style="display: none">
	<div id="job-list-audio-dialog-tabs"  style="font-size:0.85em">
		<ul>
			<li><a href="#job-list-audio-dialog-tabs-1">File details</a></li>
			<li><a href="#job-list-audio-dialog-tabs-2">Download history</a></li>
		</ul>
		<div id="job-list-audio-dialog-tabs-1">
			<p>Loading...</p>
		</div>
		<div id="job-list-audio-dialog-tabs-2">
			<p>File download history goes here...</p>
		</div>
	</div>
</div>

<div id="job-list-audio-container" style="width:100%">
	<form id="job-list-audio-form">
	<table class="index" id="job-list-audio-tbl_audiojobs">
		<thead>
			<tr>
				<th style="width:40px">ID</th>
				<th>&nbsp;</th>
				<th style="width:100px">
                    Status
                </th>
                <th>&nbsp;</th>
				<th>
                    File name
                </th>
				<th>Service</th>
                <th>Turnaround</th>
				<th style="width:75px">Length</th>
				<th>&nbsp;</th>
				<th style="width:95px">Due Date</th>
				<th>&nbsp;</th>
				<th style="width:100px">Audio</th>
				<th style="width:100px">Transcripts</th>
			</tr>
		</thead>
		<tbody>
			<?php
            if (count($this->audioJobs) > 0)
            {
                foreach ($this->audioJobs as $audioJob)
                {
                    $audioJob['job'] = $this->job;
                    echo $this->partial('audio-job/_listForJobRowClient.phtml', 'default', $audioJob);
                }
            }
            ?>
		</tbody>
		<tfoot id="footer-search">
			<tr>
				<th>&nbsp;</th>
                <th>&nbsp;</th>
                <th><input type="text" name="search_status" value="Search status" class="search_init ui-widget-content ui-corner-all" /></th>
				<th>&nbsp;</th>
				<th><input type="text" name="search_title" value="Search sound file title" class="search_init ui-widget-content ui-corner-all" /></th>
				<th>&nbsp;</th>
                <th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
				<th>&nbsp;</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
		</tfoot>
	</table>
	</form>
</div>
<script>
var asInitVals = new Array();
var audioJobTable;


//var audioJobTable;
$(document).ready(function() {

    function childAudio()
    {
        $('.child-audio-job').each(function()
        {
            var nextRow = $(this).next();
            if (!nextRow.hasClass('child-audio-job'))
            {
                $(this).addClass('child-audio-job-last');
            }
        })
    }

    childAudio();

	$('#job-list-audio-dialog').dialog({
		autoOpen: false,
		title: 'File information...',
		modal: true,
		width: 400,
		height: 400
	});
	$('#job-list-audio-dialog-tabs').tabs();

	$('#job-list-transcription-dialog').dialog({
		autoOpen: false,
		title: 'View transcription files',
		modal: true,
		width: 700,
		height: 550
	});

    audioJobTable = $('#job-list-audio-tbl_audiojobs').dataTable({
    	"iDisplayLength": 50,
        "bJQueryUI": true,
	    "bAutoWidth": false,
        "bPaginate": false,
        "sPaginationType": "full_numbers",
        "bStateSave": true,
        "oLanguage": {
            "sSearch": "Search all columns:",
            "sEmptyTable": "No audio jobs available"
        },
        "aaSorting" : [[0, "asc"]],
        "aoColumnDefs": [
						{ "iDataSort": 1		, "aTargets": [ 0 ] }, // id sort
             			{ "iDataSort": 3		, "aTargets": [ 2 ] }, // priority sort
             			{ "bVisible" : false	, "aTargets": [ 1,3,8,10 ] },
             			{ "sType"	 : "numeric", "aTargets": [ 1 ] },
             			{ "sType"	 : "numeric", "aTargets": [ 3 ] },
             			{ "bSortable": false	, "aTargets": [ 8 ] }
        ]
    });


    $("tfoot input").keyup( function () {
        /* Filter on the column (the index) of this element */
        // note: add +4 to the index.value as there is no input in col 0 so the index of the text input doesn't match the index of the column being queried
        audioJobTable.fnFilter(this.value, $("tfoot input").index(this)+7);
    } );


    /*
     * Support functions to provide a little bit of 'user friendlyness' to the textboxes in
     * the footer
     */
    $("tfoot input").each( function (i) {
        asInitVals[i] = this.value;
    } );

    $("tfoot input").focus( function () {
        if ( this.className == "search_init ui-widget-content ui-corner-all" )
        {
            this.className = "";
            this.value = "";
        }
    } );

    $("tfoot input").blur( function (i) {
        if ( this.value == "" )
        {
            this.className = "search_init ui-widget-content ui-corner-all";
            this.value = asInitVals[$("tfoot input").index(this)];
        }
    } );

} );

function stopBubble(event) {
   	if (event){
   		event.stopPropagation();
   	} else {
   		window.event.cancelBubble = true;
  	}
}

function showTranscriptionFiles(audio_job_id)
{
	$('#job-list-transcription-dialog').dialog('open');

	var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'show-transcription-file-list'), null, true); ?>/audio_job_id/" + audio_job_id;
	$.ajax({
		type: "GET",
	  	url: url,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {
	  	$("#job-list-transcription-dialog-container").html(msg.html);
	  	$( "#job-list-transcription-dialog-btn_cancel" ).button();
	});
}

function showSoundFile(audio_job_id)
{
	$('#job-list-audio-dialog').dialog('open');
	$('#job-list-audio-dialog-tabs-1').html('<p>Loading...</p>');

	var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'show-sound-file-details'), null, true); ?>/audio_job_id/" + audio_job_id;
	$.ajax({
		type: "GET",
	  	url: url,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {
	  	$("#job-list-audio-dialog-tabs-1").html(msg.html);
	  	$("#job-list-audio-dialog-tabs-2").html(msg.html_history);
	});
}

function doSoundFileDownload(audio_job_id)
{
	var url ="<?php echo $this->url(array('controller' => 'audio-job', 'action' => 'download'), null, true); ?>/id/" + audio_job_id;
	window.location.href = url;
}

function doTranscriptionFileDownload(transcription_file_id)
{

	var url ="<?php echo $this->url(array('controller' => 'transcription-file', 'action' => 'setup-download'), null, true); ?>/id/" + transcription_file_id;

	$.ajax({
		type: "GET",
	  	url: url,
	  	cache: false,
	  	dataType: "json"
	}).success(function( msg ) {
	  	if (msg.html != '') {
	  		//$("#job-list-audio-typist-" + audio_job_id).html(msg.html);
	  		//TODO: what ahppens if error?
	  	}

		var url ="<?php echo $this->url(array('controller' => 'transcription-file', 'action' => 'download'), null, true); ?>/id/" + transcription_file_id;
	  	window.location.href = url;

	});

}

function launchEdit(source, title, width)
{
    if (width == undefined)
    {
        width = 1000;
    }
    height = 600;
    var left = (screen.width - width) / 2;
    var top  = (screen.height - height) / 2;
    infoWindow = window.open(source, title, "width=" + width + ", height=" + height + ", location=no, menubar=no, resizable=yes, scrollbars=yes, status=yes, titlebar=no, toolbar=no, top="+top+", left="+left);
    if (infoWindow.opener == null)
    {
        infoWindow.opener = self;
    }
    infoWindow.focus();
    if (event)
    {
        event.cancelBubble = true;
    }
}
</script>