<?php if ($this->data['proofreader_count'] == 1):?>

<?php if (!is_null($this->data['due_date_unix']) && $this->data['due_date_unix'] < time()): ?>
<span style="color:red">!!</span>
<?php endif;?>
<a href="#" onclick="showAssignProofreader(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_proofreaders_id']?>);return false;"><?php echo $this->escape($this->data['proofreader_name']); ?></a>

<br />

<span style="margin-top: 5px" title="Receipt confirmed?">R:&nbsp;</span>
<span>
<?php if(isset($this->data['accepted']) && $this->data['accepted']):?>
	<img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png" />
<?php else:?>
	<a href="#" onclick="proofreaderAccept(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_proofreaders_id']?>);return false;">
		<img src="<?php echo $this->baseUrl(); ?>/images/icons/cross.png" />
	</a>
<?php endif;?>
</span>

<?php if($this->data['accepted']):?>
    <span style="margin-top: 5px" title="Audio downloaded?">D:&nbsp;</span>
    <span>
    <?php if($this->data['downloaded']):?>
        <img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png" title="Audio downloaded"/>
        <?php else:?>
        <a href="#" onclick="proofreaderConfirmDownload(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_proofreaders_id']?>);return false;">
            <img src="<?php echo $this->baseUrl(); ?>/images/icons/cross.png" title="Audio not downloaded"/>
        </a>
        <?php endif;?>
</span>
<?php endif;?>

<a href="#" onclick="showAssignMultipleProofreader(<?php echo $this->data['id']?>, 'create'); return false;">Split file?</a>

<?php elseif($this->data['proofreader_count'] > 1): ?>

    <?php $assignedProofreaderCount = $this->assignedProofreadersCount($this->data['id']); ?>
    <?php if ($this->data['proofreader_count'] == $assignedProofreaderCount): ?>
       File is split (<?php echo $this->escape($this->data['proofreader_count']) ?>)
    <?php else: ?>
        !!File is split (<?php echo $this->escape($this->data['proofreader_count']) ?>/<?php echo $assignedProofreaderCount; ?>)
    <?php endif; ?>
	<br />
	<a href="#" onclick="showAssignMultipleProofreader(<?php echo $this->data['id']?>, 'edit');return false;">
		<span style="font-size:75%; color: #4E4E4E;">View proofreaders</span>
	</a>
<?php else:?>
    <a href="#" onclick="showAssignProofreader(<?php echo $this->data['id']?>);return false;">Assign proofreader?</a>
    <br />
    <a href="#" onclick="showAssignMultipleProofreader(<?php echo $this->data['id']?>, 'create');return false;">Split file?</a>
<?php endif;?>