<?php

if ( $this->data['hasSubStandard'] )
{
    ?>
    <span class="has-substandard">*</span>
<?php
}

?>

<?php if ($this->data['typist_count'] == 1):?>

		<?php if (!is_null($this->data['typist_due_date']) && strtotime($this->data['typist_due_date']) < time()): ?>
		<span style="color:red">!!</span>
		<?php endif;?>
		<a href="#" onclick="showAssignTypist(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_typists_id']?>);return false;"><?php echo $this->escape($this->data['typist_name']); ?></a>


	    <span style="margin-top: 5px" title="Receipt confirmed?">R:&nbsp;</span>
		<span>
		<?php if($this->data['accepted']):?>
			<img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png" title="Receipt confirmed"/>
		<?php else:?>
			<a href="#" onclick="typistAccept(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_typists_id']?>);return false;">
				<img src="<?php echo $this->baseUrl(); ?>/images/icons/cross.png" title="Receipt not confirmed"/>
			</a>
		<?php endif;?>
		</span>
		<?php if($this->data['accepted']):?>
		<span style="margin-top: 5px" title="Audio downloaded?">D:&nbsp;</span>
			<span>
			<?php if($this->data['downloaded']):?>
			<img src="<?php echo $this->baseUrl(); ?>/images/icons/tick.png" title="Audio downloaded"/>
			<?php else:?>
			<a href="#" onclick="typistConfirmDownload(<?php echo $this->data['id']?>, <?php echo $this->data['audio_jobs_typists_id']?>);return false;">
				<img src="<?php echo $this->baseUrl(); ?>/images/icons/cross.png" title="Audio not downloaded"/>
			</a>
			<?php endif;?>
		</span>
		<?php endif;?>
		<a href="#" onclick="showAssignMultipleTypist(<?php echo $this->data['id']?>, 'create'); return false;">Split file?</a>

<?php elseif($this->data['typist_count'] > 1): ?>
    <?php $assignedTypistCount = $this->assignedTypistsCount($this->data['id']); ?>
    <?php if ($this->data['typist_count'] == $assignedTypistCount): ?>
        File is split (<?php echo $this->escape($this->data['typist_count']) ?>)
    <?php else: ?>
        !!File is split (<?php echo $this->escape($this->data['typist_count']) ?>/<?php echo $assignedTypistCount; ?>)
    <?php endif; ?>
        <br />
        <a href="#" onclick="showAssignMultipleTypist(<?php echo $this->data['id']; ?>, 'edit');return false;">
            <span style="font-size:75%; color: #4E4E4E;">View typists</span>
        </a>
<?php else:?>
    <a href="#" onclick="showAssignTypist(<?php echo $this->data['id']?>);return false;">Assign typist?</a>
    <br />
    <a href="#" onclick="showAssignMultipleTypist(<?php echo $this->data['id']?>, 'create');return false;">Split file?</a>
<?php endif;?>