
<div id="login-box" class="amnesia">
	<h1>
		<img src="/images/logo2.png" alt="Take Note" />
	</h1>
	<h2>
		<?php echo $this->translate('Forgotten password?'); ?>
	</h2>

    <?php echo $this->flashMessenger(); ?>
       
    <form action="<?php echo $this->url(array('controller' => 'amnesia', 'action' => 'send-password'), null, true); ?>" method="post" name="loginForm" id="loginForm">
    
		<p class="info"><?php echo $this->translate('Please enter your email address to reset your password. You will need to re-enter a Passphrase after your password has been reset'); ?></p>
    	 
		<input type="text" name="email" id="email" placeholder="<?php echo $this->translate('Email address'); ?>" /> </label>
		
        <?php if ($this->hasFailed): ?><span class="error">The email you entered is incorrect</span><?php endif; ?>

        <input type="image" name="submit" id="submit1" value="<?php echo $this->translate('Request Password'); ?>" src="/images/requestpassword_button.png" />
		
		<a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'auth'), null, true); ?>" id="forgotten-password">Back to login</a>
    </form>
</div>


<script>
	$(function() {		
		$('#login-box').find('input[type="text"], textarea').each(function(){
			this.defaultValue = this.value;
			$(this).click(function(){
				if(this.value == this.defaultValue){
					$(this).val("");
				}
			});
			$(this).blur(function(){
				if(this.value == ""){
					$(this).val(this.defaultValue);
				}
			});
		});
		
		
		if(!Modernizr.input.placeholder){

			$('[placeholder]').focus(function() {
				var input = $(this);
				if (input.val() == input.attr('placeholder')) {
					input.val('');
					input.removeClass('placeholder');
				}
			}).blur(function() {
				var input = $(this);
				if (input.val() == '' || input.val() == input.attr('placeholder')) {
					input.addClass('placeholder');
					input.val(input.attr('placeholder'));
				}
			}).blur();
			
			$('[placeholder]').parents('form').submit(function() {
				$(this).find('[placeholder]').each(function() {
					var input = $(this);
					if (input.val() == input.attr('placeholder')) {
						input.val('');
					}
				})
			});
		
		}
		
	});
</script>
